# This file was generated by GoReleaser. DO NOT EDIT.
cask "portview" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "5a3793532243fffb89096c45d03231131738e933625b1ddf07c06759030ecb5c"
      url "https://github.com/jeramiahgcoffey/portview/releases/download/v#{version}/portview_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dc61f5366ce7740ffd46322d003152eebc38eb0ee904be7a1896370821aaeb6c"
      url "https://github.com/jeramiahgcoffey/portview/releases/download/v#{version}/portview_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2a4d0075ffa2bf8620da66072ce86eb716b2bab8fc421630da50ae11e7ef0dd0"
      url "https://github.com/jeramiahgcoffey/portview/releases/download/v#{version}/portview_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f46b2c02d0a9a92ac82d081fd38095a4563cec237358fa026bfa014c21ceb79e"
      url "https://github.com/jeramiahgcoffey/portview/releases/download/v#{version}/portview_#{version}_linux_arm64.tar.gz"
    end
  end

  name "portview"
  desc "A TUI for discovering and managing localhost dev servers"
  homepage "https://github.com/jeramiahgcoffey/portview"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "portview"

  # No zap stanza required

end
