# This file was generated by GoReleaser. DO NOT EDIT.
cask "portview" do
  version "0.0.1-test"

  on_macos do
    on_intel do
      sha256 "6713b9380f38d74176cda07b722c90905d456f3d26278e08724bdeccfad678fb"
      url "https://github.com/jeramiahgcoffey/portview/releases/download/v#{version}/portview_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "10161624fbff0d6a91403845524fa138c00fe40ff30f39b38376245c323760f0"
      url "https://github.com/jeramiahgcoffey/portview/releases/download/v#{version}/portview_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "624471de79dcce4e75a045b7718d0322db1d76b8112a058e1e9df31ab3d423f8"
      url "https://github.com/jeramiahgcoffey/portview/releases/download/v#{version}/portview_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c2847fe039be67611eb73fb898cb3d6ec7b7bc671d7acb1ec2615ba8e142f730"
      url "https://github.com/jeramiahgcoffey/portview/releases/download/v#{version}/portview_#{version}_linux_arm64.tar.gz"
    end
  end

  name "portview"
  desc "A TUI for discovering and managing localhost dev servers"
  homepage "https://github.com/jeramiahgcoffey/portview"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "portview"

  # No zap stanza required

end
